### ISSUE TITLE
Publish LRCGET to winget and auto-update via github-action

### ISSUE THREAD

**Issue by jo-chemla** [tranxuanthang/lrcget#180]
### Description

I've just made a PR here, awaiting merge, https://github.com/microsoft/winget-pkgs/pull/212751 in order to publish a winget package for LRCGET so it can be installed via `winget install lrcget` - note two similar PRs were closed without merging due to the validation process breaking, will see if this one goes through.

It could be useful to add a github action on this repo so that the winget `LRCLIB.LRCGET` package gets updated on every github release. Here is a reference article based on [Winget-Releaser@v2 Github Action](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-) 

Below is an action yml files made to keep the winget package up-to-date on every github release, via Github Actions. 

Requires:
 - You will need to create a classic Personal Access Token (PAT) with public_repo scope.
 - This token should be added as a repository secret by creating a [new repo secret](https://github.com/Jacalz/rymdport/settings/secrets/actions/new) with name WINGET_ACC_TOKEN and value the token
 - Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account/organization as the project's repository. If you are forking winget-pkgs on a different account (e.g. bot/personal account), you can use the fork-user input to specify the username of the account where the fork is present.

```yaml
name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: LRCLIB.LRCGET
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: ' *x64\-setup\.exe$' 
```
